### ISSUE TITLE
Implement an undo command

### ISSUE THREAD

**Issue by davidobber** [brenzy/gpx-smoother-vue#26]
It would be nice to save the state of work in progress and provide the ability to undo the last commands. This way the user can avoid restarting all the activity from scratch.
Thank you!

**Comment by brenzy** [comment]
Hi @davidobber.  I have had other interest in this feature, so yes I can take a look at adding it when I have some time.

**Comment by brenzy** [comment]
@davidobber, the feature was added in PR #28, Version 1.8.0.
